# Generated by Django 3.2.6 on 2021-08-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number1', models.FloatField(default=0)),
                ('number2', models.FloatField(default=0)),
            ],
        ),
    ]
