# Generated by Django 3.2.6 on 2021-08-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_math_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='add_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maths.math_type'),
        ),
    ]
