# Generated by Django 3.2.6 on 2021-08-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_math_add_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='add_sign',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maths.math_type'),
        ),
    ]
