# Generated by Django 3.2.6 on 2021-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0002_alter_order1_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
