# Generated by Django 3.2.6 on 2021-08-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0004_alter_customer1_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order1',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store1.customer1'),
        ),
    ]
