# Generated by Django 3.2.6 on 2021-08-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0005_alter_order1_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem1',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store1.order1'),
        ),
        migrations.AlterField(
            model_name='orderitem1',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store1.product1'),
        ),
    ]
